export enum MomentErrorCode {
  NOT_FOUND = 'NOT_FOUND',
  UNAUTHORIZED = 'UNAUTHORIZED',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  UPSTREAM_SERVICE_ERROR = 'UPSTREAM_SERVICE_ERROR',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}
